# Generated by Django 4.0.1 on 2022-02-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField()),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_date_work', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('media_data', models.TextField(db_collation='utf8mb4_bin')),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'admin_applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('media_data', models.TextField(blank=True, db_collation='utf8mb4_bin', null=True)),
                ('applicants_details', models.TextField(blank=True, db_collation='utf8mb4_bin', null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
                ('final_date', models.DateTimeField(blank=True, null=True)),
                ('is_moderate', models.IntegerField()),
                ('problem_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('base_rate', models.IntegerField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('views_count', models.IntegerField()),
            ],
            options={
                'db_table': 'applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'applications_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'application_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractorsProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'contractors_problems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExecutiveAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mnemomic_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('responsible_person', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('hash_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email_administration', models.CharField(blank=True, max_length=255, null=True)),
                ('tg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('web_site_link', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_information', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=20)),
                ('work_schedule', models.TextField(blank=True, db_collation='utf8mb4_bin', null=True)),
                ('is_email_alert', models.IntegerField()),
                ('is_sms_alert', models.IntegerField()),
                ('is_generate_daily_report', models.IntegerField()),
                ('is_visible', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'executive_authority',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MailingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_address', models.CharField(max_length=30)),
                ('mailing_type', models.IntegerField()),
                ('status', models.IntegerField()),
                ('template_name', models.CharField(blank=True, max_length=30, null=True)),
                ('template_object', models.TextField(blank=True, db_collation='utf8mb4_bin', null=True)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mailing_queue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField()),
                ('author_name', models.CharField(max_length=30)),
                ('type', models.IntegerField()),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('life_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('is_visible', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('stories_type', models.IntegerField()),
                ('views_count', models.IntegerField()),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mnemonic_name', models.CharField(max_length=100)),
                ('hash_tag', models.CharField(max_length=100)),
                ('icon_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.IntegerField()),
                ('is_visible', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'problem_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_available', models.SmallIntegerField()),
                ('position', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('mnemomic_name', models.CharField(blank=True, max_length=50, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SavedCoord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.IntegerField()),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('media_data', models.TextField(blank=True, db_collation='utf8mb4_bin', null=True)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'saved_coord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokenBlocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'token_blocklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_email_alert', models.IntegerField()),
                ('is_sms_alert', models.IntegerField()),
                ('is_anonym', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'user_profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('sms_code', models.CharField(blank=True, max_length=4, null=True)),
                ('email_code', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_confirm_date', models.DateTimeField(blank=True, null=True)),
                ('email_confirm_date', models.DateTimeField(blank=True, null=True)),
                ('ban_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.IntegerField()),
                ('is_admin', models.IntegerField()),
                ('is_stuff', models.IntegerField()),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
