# Generated by Django 4.0.1 on 2022-02-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminapplications',
            options={'managed': False, 'verbose_name': 'Заявка по исполнительному органу', 'verbose_name_plural': 'Заявки по исполнительным органам'},
        ),
        migrations.AlterModelOptions(
            name='applications',
            options={'managed': False, 'ordering': ('status', 'user'), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='applicationscategories',
            options={'managed': False, 'verbose_name': 'Категория заявления', 'verbose_name_plural': 'Категории заявлений'},
        ),
        migrations.AlterModelOptions(
            name='applicationstatus',
            options={'managed': False, 'verbose_name': 'Статус заявки', 'verbose_name_plural': 'Статусы заявок'},
        ),
        migrations.AlterModelOptions(
            name='contractorsproblems',
            options={'managed': False, 'verbose_name': 'Исполнительный орган', 'verbose_name_plural': 'Исполнительные органы'},
        ),
        migrations.AlterModelOptions(
            name='executiveauthority',
            options={'managed': False, 'verbose_name': 'Исполнительный орган', 'verbose_name_plural': 'Исполнительные органы'},
        ),
        migrations.AlterModelOptions(
            name='mailingqueue',
            options={'managed': False, 'verbose_name': 'Очередь', 'verbose_name_plural': 'Очередь рассылки'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'managed': False, 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='problemcategories',
            options={'managed': False, 'verbose_name': 'Категория проблем', 'verbose_name_plural': 'Категории проблем'},
        ),
        migrations.AlterModelOptions(
            name='regions',
            options={'managed': False, 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': False, 'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='savedcoord',
            options={'managed': False, 'verbose_name': 'Координаты', 'verbose_name_plural': 'Сохраненные координаты'},
        ),
        migrations.AlterModelOptions(
            name='tokenblocklist',
            options={'managed': False, 'verbose_name': 'Токен', 'verbose_name_plural': 'Токены'},
        ),
        migrations.AlterModelOptions(
            name='userprofiles',
            options={'managed': False, 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
