# Generated by Django 4.0.1 on 2022-01-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ('status', 'user'), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
